INSERT INTO PRODUTOS(NAME) VALUES ('KXT100');
INSERT INTO PRODUTOS(NAME) VALUES ('KXT200');
INSERT INTO PRODUTOS(NAME) VALUES ('KXT300');
INSERT INTO PRODUTOS(NAME) VALUES ('KXT400');

INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 1',1);
INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 1',2);
INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 2',2);
INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 2',3);
INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 3',3);
INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 3',4);
INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 4',4);
INSERT INTO PEDIDOS(DESC,PRODUTOS_ID) VALUES ('CLIENTE 4',1);
